// Generated by CoffeeScript 1.3.3
(function() {
  var cssExplain, exec, explainCssSelectors;

  exec = require('child_process').exec;

  cssExplain = require('css-explain').cssExplain;

  explainCssSelectors = function(selectors) {
    var categories, keys, report, scores, total, _i, _len, _name, _ref, _ref1;
    if (!(selectors && selectors.length)) {
      return;
    }
    total = 0;
    categories = {
      id: 0,
      "class": 0,
      tag: 0,
      universal: 0
    };
    scores = {
      1: 0,
      2: 0,
      3: 0,
      4: 0,
      5: 0,
      6: 0,
      7: 0,
      8: 0,
      9: 0,
      10: 0
    };
    keys = {};
    _ref = cssExplain(selectors);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      report = _ref[_i];
      categories[report.category] += 1;
      scores[report.score] += 1;
      if ((_ref1 = keys[_name = report.key]) == null) {
        keys[_name] = 0;
      }
      keys[report.key] += 1;
      total++;
    }
    return {
      total: total,
      categories: categories,
      scores: scores,
      keys: keys
    };
  };

  exports.profile = function(url, callback) {
    return exec("phantomjs --web-security=no " + __dirname + "/runner.js " + url, function(error, stdout, stderr) {
      var k, name, props, report, v, _ref, _ref1;
      if (error) {
        return callback(error);
      } else {
        try {
          report = JSON.parse(stdout);
        } catch (e) {
          callback(new Error(stdout));
          return;
        }
        report.cssExplain = explainCssSelectors(report.cssRules);
        report.jquery.find.explain = explainCssSelectors((function() {
          var _ref, _results;
          _ref = report.jquery.find.calls;
          _results = [];
          for (k in _ref) {
            v = _ref[k];
            _results.push(k);
          }
          return _results;
        })());
        report.jquery.match.explain = explainCssSelectors((function() {
          var _ref, _results;
          _ref = report.jquery.match.calls;
          _results = [];
          for (k in _ref) {
            v = _ref[k];
            _results.push(k);
          }
          return _results;
        })());
        _ref = report.jquery.event;
        for (name in _ref) {
          props = _ref[name];
          if ((_ref1 = props.selectors) != null ? _ref1.length : void 0) {
            report.jquery.event[name].explain = explainCssSelectors(props.selectors);
          }
        }
        return callback(void 0, report);
      }
    });
  };

}).call(this);
